---
default_stages: [commit, push]
default_language_version:
    python: python3

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: debug-statements
          - id: check-toml
          - id: detect-private-key

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.32.0
      hooks:
          - id: yamllint
            entry: yamllint --strict .
            types: [yaml]
            exclude: ^[^\/]+\/.venv\/lib\/?(?:[^\/]+\/?)*$

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/PyCQA/autoflake
      rev: v2.2.1
      hooks:
          - id: autoflake

    - repo: https://github.com/ambv/black
      rev: 23.11.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8

    - repo: https://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black]

    # - repo: local
    #   hooks:
    #       - id: pyright
    #         name: pyright
    #         entry: poetry run pyright --warnings
    #         language: node
    #         pass_filenames: false
    #         types: [python]
    #         exclude: service.py
    #         additional_dependencies: [pyright@1.1.190]
