repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: debug-statements
    - id: check-toml
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)
  - repo: local
    hooks:
    - id: pyright
      name: pyright
      entry: "poetry run pyright --warnings"
      language: node
      pass_filenames: false
      types: [python]
      additional_dependencies: ['pyright@1.1.190']