---
name: Integration Test

on:
    push:
    pull_request:
        branches:
            - dependabot/**

jobs:
    python-matrix:
        name: Test against Python versions
        strategy:
            fail-fast: false
            matrix:
                version: ['3.10', '3.11', '3.12']
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - id: pre-commit
              uses: Kristina-Pianykh/poetry-pre-commit-cache@v1.2
              with:
                  python-version: ${{ matrix.version }}

            - name: Start Containers
              run: docker compose up -d --build

            - name: Sleep for 2 Minutes
              uses: jakejarvis/wait-action@master
              with:
                  time: 120s

            - name: Test API Reachability
              id: test_api
              run: |
                  echo "http_status=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8000)" >> $GITHUB_OUTPUT

            - name: Test Step
              run: |
                  echo "Status code: ${{ steps.test_api.outputs.http_status}}"

            - name: Stop Containers on Status Code 200
              if: steps.test_api.outputs.http_status == 200
              run: docker compose down

            - name: Fail Job on unreachable API
              if: steps.test_api.outputs.http_status != 200
              run: exit 1
